name: Delete Cypress Snapshots Artifacts

on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts from last successful workflow
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq '.artifacts[] | .name'

      - name: List all artifacts with the name "cypress-snapshots"
        id: list-artifacts
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
              | jq '[.artifacts[] | select(.name == "cypress-snapshots")]' > artifacts.json

          ARTIFACT_COUNT=$(jq 'length' artifacts.json)
          echo "artifact_count=$ARTIFACT_COUNT" >> $GITHUB_ENV

      - name: Delete artifacts if any exist
        if: env.artifact_count != '0'
        run: |
          for id in $(jq -r '.[].id' artifacts.json); do
            echo "Deleting artifact with ID: $id"
            curl -X DELETE -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$id"
          done

      - name: List artifacts from last successful workflow
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq '.artifacts[] | .name'

      - name: Log result
        run: |
          if [ "$ARTIFACT_COUNT" -eq 0 ]; then
            echo "No artifacts found with the name 'cypress-snapshots'."
          else
            echo "Deleted $ARTIFACT_COUNT artifacts with the name 'cypress-snapshots'."
          fi
