name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Clear snapshot cache
        run: rm -rf cypress/snapshots/*

      - name: Run Cypress tests
        run: npm run cy:test

      - name: Upload new snapshots as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-snapshots
          path: cypress/snapshots
          retention-days: 30
